server:
  port: 8080

spring:
  application:
    name: ms.recommendation

  profiles:
    active: ${ACTIVE_PROFILE:local}

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000ms
          max-attempts: 5
          max-interval: 5000ms
          multiplier: 1
        missing-queues-fatal: false

redis:
  server:
    urls: redis://localhost:6379

rabbitmq:
  queue:
    recommendation: RECOMMENDATION_QUEUE
    recommendation-dlq: RECOMMENDATION_DLQ